### ISSUE TITLE
[Lojista] Site da Loja não é aberto após clicar em Onde Comprar e dentro da loja clicar no botão para ser direcionado para o lojista

### ISSUE THREAD

**Issue by valeriamoura** [Endeavor-MPES-2021/artesan-app#20]
Site da Loja não é aberto após clicar em Onde Comprar e dentro da loja clicar no botão para ser direcionado para o lojista
Passos para reproduzir:
1- Acessar uma obra que deu match
2- Ir em Onde Comprar
3- Selecionar uma loja que vende a Obra
4- Clicar no botão para direcionar para a loja ou no botão Comprar.

Resultado encontrado: App não direciona para lojista e sim para página principal do app.
Resultado esperado: App direcionar para o site do lojista. Definir um botão válido apenas.

**Comment by rafacalandreli** [comment]
Problema resolvido.
