### ISSUE TITLE
[Cadastro de Usuário] Idioma do email de confirmação de cadastro está em inglês por padrão

### ISSUE THREAD

**Issue by valeriamoura** [Endeavor-MPES-2021/artesan-app#25]
[Cadastro de Usuário] Idioma do email de confirmação de cadastro está em inglês por padrão.
![Screen Shot 2021-11-30 at 13 38 49](https://user-images.githubusercontent.com/87383742/144089299-d2b9d255-95da-451f-8f39-c98167584396.png)

**Comment by rafacalandreli** [comment]
Problema Resolvido.
